spring.application.name=springBoot_mariaDB_thymeleaf

# db connection(mariaDB) - spring(context.xml)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=tiger

# http port number(default 8080)
server.port=8081

# JPA SQL SHOW
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

